// "https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=0&longitude=0"

import { useEffect, useState } from "react";
import { useUrlPosition } from "../hooks/useUrlPosition";
import { useCities } from "../contexts/CitiesProvider";
import { DatePicker } from "react-datepicker";
import styles from "./Form.module.css";
import Button from "./Button";
import BackButton from "./BackButton";
import Spinner from "./Spinner";
import Message from "./Message";

import "react-datepicker/dist/react-datepicker.css";
import { useNavigate } from "react-router-dom";

const BASE_URL =
  "https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=[LAT]&longitude=[LNG]";

export function convertToEmoji(countryCode) {
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt());
  return String.fromCodePoint(...codePoints);
}

function Form() {
  const navigate = useNavigate();

  const [cityName, setCityName] = useState("");
  const [country, setCountry] = useState("");
  const [date, setDate] = useState(new Date());
  const [notes, setNotes] = useState("");
  const [isLoadingGeocoding, setisLoadingGeocoding] = useState(false);
  const [emoji, setEmoji] = useState("");
  const [lat, lng] = useUrlPosition();
  const [geocodingError, setGeocodingError] = useState("");

  const { createCity, isLoading: isLoadingCity } = useCities();

  useEffect(
    function () {
      if (!lat || !lng) return; //bail out early
      async function getPositionInfo() {
        try {
          const url = BASE_URL.replace("[LAT]", lat).replace("[LNG]", lng);
          //console.log(url);
          setisLoadingGeocoding(true);
          setGeocodingError("");
          const resp = await fetch(url);
          if (!resp.ok) throw new Error("Error fetching location data");
          const data = await resp.json();
          //console.log(data);

          if (!data.countryCode)
            throw new Error("Selection not valid; select a city.");

          setCityName(data.city || data.locality || "Undetermined");
          setCountry(data.countryName);
          setEmoji(convertToEmoji(data.countryCode));

          //console.log("trying to get id: ");
          // const localityInfo = data.localityInfo.administrative.filter(
          //   (d) => d.name === data.city,
          // );
          // const id = localityInfo[0].geonameId;
          // //console.log(id);
        } catch (Error) {
          setGeocodingError(Error.message);
          //alert(Error.message);
        } finally {
          setisLoadingGeocoding(false);
        }
      }
      getPositionInfo();
    },
    [lat, lng],
  );

  async function handleSubmit(e) {
    e.preventDefault(); //keep form from actually submitting and reloading page

    if (!cityName || !date) return;

    const newCity = {
      cityName,
      country,
      emoji,
      date, //need to get from form
      notes, //need to get from for
      position: {
        lat: lat,
        lng: lng,
      },
      //id: "?", //generated by fakeAPI server
    };

    await createCity(newCity);

    navigate("/app/cities");
    //console.log(newCity);
  }

  if (!lat || !lng)
    return <Message message="Start by clicking a city on the map" />;

  if (geocodingError) return <Message message={geocodingError} />;
  if (isLoadingGeocoding) return <Spinner />;

  return (
    <form
      className={`${styles.form} ${isLoadingCity ? styles.loading : ""}`}
      onSubmit={handleSubmit}
    >
      <div className={styles.row}>
        <label htmlFor="cityName">City name</label>
        <input
          id="cityName"
          onChange={(e) => setCityName(e.target.value)}
          value={cityName}
        />
        <span className={styles.flag}>{emoji}</span>
      </div>

      <div className={styles.row}>
        <label htmlFor="date">When did you go to {cityName}?</label>

        <DatePicker
          onChange={(date) => setDate(date)}
          selected={date}
          dateFormat="MM/dd/yyyy"
          id="date"
        />
      </div>

      <div className={styles.row}>
        <label htmlFor="notes">Notes about your trip to {cityName}</label>
        <textarea
          id="notes"
          onChange={(e) => setNotes(e.target.value)}
          value={notes}
        />
      </div>

      <div className={styles.buttons}>
        <Button type="primary">Add</Button>
        <BackButton />
      </div>
    </form>
  );
}

export default Form;
